/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001f24",
        "surface-dim": "#131313",
        "on-tertiary-container": "#e4ffdb",
        "on-tertiary-fixed": "#002203",
        "on-primary": "#00363d",
        "on-background": "#e5e2e1",
        "outline-variant": "#424656",
        "primary-fixed-dim": "#00daf3",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f1f",
        "secondary-fixed-dim": "#c8c6c6",
        "outline": "#8c90a1",
        "surface-container-high": "#2a2a2a",
        "tertiary": "#00e639",
        "surface-container-low": "#1c1b1b",
        "secondary": "#c8c6c6",
        "primary": "#00daf3",
        "on-primary-fixed-variant": "#004f58",
        "inverse-primary": "#006875",
        "on-primary-container": "#e9fbff",
        "on-secondary-fixed": "#1b1c1c",
        "primary-fixed": "#9cf0ff",
        "on-tertiary-fixed-variant": "#00530e",
        "on-secondary-container": "#b6b5b4",
        "surface-bright": "#3a3939",
        "surface-variant": "#353534",
        "error-container": "#93000a",
        "primary-container": "#007e8c",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#72ff70",
        "tertiary-container": "#00841c",
        "on-secondary-fixed-variant": "#474747",
        "on-secondary": "#303030",
        "surface-tint": "#00daf3",
        "error": "#ffb4ab",
        "surface-container-highest": "#353534",
        "on-surface-variant": "#c2c6d8",
        "surface": "#131313",
        "tertiary-fixed-dim": "#00e639",
        "background": "#131313",
        "on-error": "#690005",
        "secondary-container": "#474747",
        "secondary-fixed": "#e4e2e1",
        "inverse-on-surface": "#313030",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary": "#003907"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
